{{- if .Values.argocd.grafana.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-app
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://grafana.github.io/helm-charts'
    chart: grafana
    targetRevision: 7.0.19
    helm: 
      valueFiles:
      - $values/grafana/values.yaml
      parameters:
      - name: "ingress.hosts[0]"
        value: "{{ .Values.argocd.grafana.ingress }}"
  - repoURL: 'https://github.com/StuxxNet/descomplicando-gitops-no-kubernetes-argocd'
    targetRevision: main
    ref: values
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}