apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-monitoring
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app-of-apps-monitoring
    helm:
      parameters:
      - name: "argocd.prometheus.enabled"
        value: "true"
      - name: "argocd.prometheus.ingress"
        value: "prometheus.kubernetes.docker.internal"
      - name: "argocd.grafana.enabled"
        value: "true"
      - name: "argocd.grafana.ingress"
        value: "grafana.kubernetes.docker.internal"
    repoURL: 'https://github.com/StuxxNet/descomplicando-gitops-no-kubernetes-argocd'
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
    - ServerSideApply=true