apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: matrix-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/StuxxNet/descomplicando-gitops-no-kubernetes-argocd
          revision: HEAD
          directories:
          - path: applicationset/apps/*/helm
      - git:
          repoURL: https://github.com/StuxxNet/descomplicando-gitops-no-kubernetes-argocd
          revision: HEAD
          pathParamPrefix: cfg
          files:
          - path: applicationset/configs/dev.json
  template:
    metadata:
      name: '{{index .path.segments 2}}-{{.cluster.nome}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/StuxxNet/descomplicando-gitops-no-kubernetes-argocd
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 2}}'
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true