apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pullrequest-app-set
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        owner: StuxxNet
        repo: descomplicando-gitops-no-kubernetes-argocd
      requeueAfterSeconds: 60
  template:
    metadata:
      name: 'stack-apps-{{ branch_slug }}-{{ number }}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/StuxxNet/descomplicando-gitops-no-kubernetes-argocd
        targetRevision: '{{ head_sha }}'
        path: app-of-apps/
        helm:
          parameters:
            - name: argocd.giropopsSenhas.enabled
              value: "true"
            - name: argocd.randomLogger.enabled
              value: "true"
      destination:
        server: https://kubernetes.default.svc
        namespace: 'app-of-apps-{{ branch_slug }}-{{ number }}'
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true