apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: first-app-set
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/StuxxNet/descomplicando-gitops-no-kubernetes-argocd
      revision: HEAD
      directories:
      - path: applicationset/apps/*/helm
  template:
    metadata:
      name: '{{index .path.segments 2}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/StuxxNet/descomplicando-gitops-no-kubernetes-argocd
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 2}}'
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true